name: publish CSharp.Skeleton Template to nuget
on:
  push:
    branches:
      - main
    paths:
      - "CSharpSkeleton.nuspec"
jobs:
  publish:
    name: list on nuget
    runs-on: windows-latest
    steps:
      - name: ğŸ›‘ Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v2

      - uses: nuget/setup-nuget@v1
        with:
          nuget-version: "5.x"

      - name: ğŸ“¦ Package the template
        run: nuget pack CSharpSkeleton.nuspec

      - name: ğŸ” Publish to nuget.org
        run: nuget push CSharpSkeleton.Template.*.nupkg -src https://api.nuget.org/v3/index.json ${{secrets.NUGET_API_KEY}}
